# ===================================
# BASE DE DATOS SQLITE
# ===================================
spring.datasource.url=jdbc:sqlite:ordersystem.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# ===================================
# JPA / HIBERNATE
# ===================================
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===================================
# SERVIDOR
# ===================================
server.port=8080

# ===================================
# JACKSON
# ===================================
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=America/Bogota

# ===================================
# LOGGING
# ===================================
logging.level.com.steven.OrderSystem=DEBUG
logging.level.org.springframework.web=INFO

# ===================================
# ERRORES
# ===================================
server.error.include-message=always
